# Generated by Django 2.2.3 on 2019-07-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_desc', models.TextField()),
                ('date_from', models.DateTimeField(verbose_name='date from')),
                ('date_to', models.DateTimeField(verbose_name='date to')),
            ],
        ),
    ]
